contacts/apps/core/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from contacts.apps.core.views import DashBoardPage, AllContacts, ajax_get_all_contacts, \
    AjaxContactChangeModal, ajax_delete_contact_modal, ajax_add_contact_modal, upload_csv_file, \
    ajax_add_contact_csv, ajax_add_contact_vero, AllUsers, ajax_clients_datatable

urlpatterns = [
    url(r'^$', login_required(DashBoardPage.as_view()), name='dashboard'),
    url(r'^all_contacts/$', login_required(AllContacts.as_view()), name='all_contacts'),
    url(r'^all_users/$', login_required(AllUsers.as_view()), name='all_users'),
    url(r'^ajax_get_all_contacts/$', login_required(ajax_get_all_contacts), name='ajax_get_all_contacts'),
    url(r'^ajax_clients_datatable/$', login_required(ajax_clients_datatable), name='ajax_clients_datatable'),
    url(r'^ajax_contact_change_modal/$', login_required(AjaxContactChangeModal.as_view()),
        name='ajax_contact_change_modal'),
    url(r'^ajax_delete_contact_modal/$', login_required(ajax_delete_contact_modal), name='ajax_delete_contact_modal'),
    url(r'^ajax_add_contact_modal/$', login_required(ajax_add_contact_modal), name='ajax_add_contact_modal'),
    url(r'^upload_csv_file/$', login_required(upload_csv_file), name='upload_csv_file'),
    url(r'^ajax_add_contact_csv/$', login_required(ajax_add_contact_csv), name='ajax_add_contact_csv'),
    url(r'^ajax_add_contact_vero/$', login_required(ajax_add_contact_vero), name='ajax_add_contact_vero'),
]

contacts/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import logout

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    # admin view
    url(r'^admin/', admin.site.urls),
    # accounts
    url(r'^', include('contacts.apps.accounts.urls', namespace="accounts")),
    # core
    url(r'^', include('contacts.apps.core.urls', namespace="core")),
    url(r'^logout.*', logout, {'next_page': '/login/'}, name='logout'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()

contacts/apps/core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from contacts.apps.accounts.models import UserProfile
from datetime import datetime


# Create your models here.
class Contacts(models.Model):
    user_profile = models.ForeignKey(UserProfile)
    contact_name = models.CharField(max_length=30, blank=False)
    contact_surname = models.CharField(max_length=30, blank=False)
    city_name = models.CharField(max_length=30, blank=True)
    country_name = models.CharField(max_length=30, blank=True)
    phone_number = models.CharField(max_length=15, blank=False)
    email_contact = models.EmailField(blank=False)
    date_birthday = models.DateField(null=False, blank=True)
    date_add = models.DateField(default=datetime.now())

contacts/apps/core/forms.py
from django import forms
from contacts.apps.core.models import Contacts
from contacts.apps.accounts.models import UserProfile


class ContactsAddForm(forms.Form):
    contact_id = forms.IntegerField()
    contact_name = forms.CharField(max_length=30, required=True)
    contact_surname = forms.CharField(max_length=30, required=True)
    contact_city = forms.CharField(max_length=30, required=False)
    contact_country = forms.CharField(max_length=30, required=False)
    contact_phone = forms.CharField(max_length=15, required=False)
    contact_email = forms.EmailField(required=True)
    contact_b_date = forms.DateField(required=False)
    contact_add_date = forms.DateField(required=True)

    def clean(self):
        form_data = self.cleaned_data
        return form_data

contacts/apps/core/views.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
import json
import os
import csv
import requests
from django.shortcuts import render
from django.views.generic import View
from django.contrib.auth.models import User
from contacts.apps.core.models import Contacts
from contacts.apps.accounts.models import UserProfile
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponse
from django.utils.datastructures import MultiValueDictKeyError
from datetime import datetime, timedelta, date
from contacts.apps.core.forms import ContactsAddForm
from django.core.urlresolvers import reverse
from django.http.response import HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
from contacts.settings import BASE_DIR
from django.core.validators import validate_email
from django.core.exceptions import ValidationError


# Create your views here.
def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")


def email(value):
    try:
        validate_email(value)
        return True
    except (ValidationError), e:
        return False


def date_validate(date_text):
    try:
        datetime.strptime(date_text, '%Y-%m-%d')
        return True
    except ValueError:
        return False


class DashBoardPage(View):
    template_name = 'dashboard.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_superuser:
            user_profile = UserProfile.objects.filter(user=request.user)
            data = {
                'count_of_all_users': User.objects.all().count(),
                'count_of_all_contacts': Contacts.objects.filter(user_profile=user_profile).count()
            }
        else:
            user_profile = UserProfile.objects.filter(user=request.user)
            data = {
                'count_of_all_contacts': Contacts.objects.filter(user_profile=user_profile).count()
            }
        return render(request, self.template_name, data)


class AllContacts(View):
    template_name = 'all_contacts.html'

    def get(self, request, *args, **kwargs):
        active_city = []
        active_country = []
        if request.user.is_superuser:
            contacts_filter = Contacts.objects.all().order_by('-id')
        else:
            user_profile = UserProfile.objects.filter(user=request.user)
            contacts_filter = Contacts.objects.filter(user_profile=user_profile)
        for row in contacts_filter:
            if not row.city_name in active_city:
                active_city.append(row.city_name)
            if not row.country_name in active_country:
                active_country.append(row.country_name)
        data = {
            'city_name': active_city,
            'country_name': active_country,
            'today': datetime.today().strftime('%Y-%m-%d')
        }
        return render(request, self.template_name, data)


def ajax_get_all_contacts(request):
    user_profile = UserProfile.objects.get(user=request.user)
    ajax_response = {'sEcho': '', 'aaData': [], 'iTotalRecords': 0, 'iTotalDisplayRecords': 0}
    try:
        ajax_type = request.GET['type']
    except MultiValueDictKeyError:
        ajax_type = ''
    if ajax_type == 'dashboard':
        contacts = Contacts.objects.filter(user_profile=user_profile).order_by('contact_name')[:10]
    else:
        if request.user.is_superuser:
            contacts = Contacts.objects.all().order_by('-id')
        else:
            contacts = Contacts.objects.filter(user_profile=user_profile).order_by('-contact_name')
    # filters
    city_filter = request.GET.get('sSearch_0')
    country_filter = request.GET.get('sSearch_1')
    if city_filter and city_filter != "0":
        contacts = contacts.filter(city_name=city_filter)
    if country_filter and country_filter != "0":
        contacts = contacts.filter(country_name=country_filter)
    sort_data = request.GET.get('iSortCol_0')
    metod_sort = request.GET.get('sSortDir_0')
    char_sort = ''
    if metod_sort == 'desc': char_sort = '-'
    if sort_data == '8':
        contacts = contacts.order_by(char_sort+'date_add')
    # getting lens of response
    ajax_response['iTotalRecords'] = len(contacts)
    ajax_response['iTotalDisplayRecords'] = len(contacts)
    if ajax_type == 'dashboard':
        for contact in contacts:
            ajax_response['aaData'].append([
                contact.id,
                contact.contact_name,
                contact.contact_surname,
                contact.city_name,
                contact.country_name,
                contact.phone_number,
                contact.email_contact,
                contact.date_birthday.strftime('%Y-%m-%d'),
                contact.date_add.strftime('%Y-%m-%d')
            ])
    else:
        start = int(request.GET['iDisplayStart'])
        length = int(request.GET['iDisplayLength'])
        for contact in contacts[start:start + length]:
            if request.user.is_superuser:
                user = str(contact.user_profile)
            else:
                user = ''
            ajax_response['aaData'].append([
                contact.id,
                contact.contact_name,
                contact.contact_surname,
                contact.city_name,
                contact.country_name,
                contact.phone_number,
                contact.email_contact,
                contact.date_birthday.strftime('%Y-%m-%d'),
                contact.date_add.strftime('%Y-%m-%d'),
                user
            ])
    return HttpResponse(json.dumps(ajax_response), content_type='application/json')


class AjaxContactChangeModal(View):

    def get(self, request, *args, **kwargs):
        contact_id = int(request.GET['contact_id'])
        contact = Contacts.objects.get(pk=contact_id)
        ajax_response = {
                        "contact_id": contact_id,
                         "contact_name": contact.contact_name,
                         "contact_surname": contact.contact_surname,
                         "city": contact.city_name,
                         "country": contact.country_name,
                         "phone": contact.phone_number,
                         "email": contact.email_contact,
                         "birthday": contact.date_birthday.strftime('%Y-%m-%d'),
                         "date_add": contact.date_add.strftime('%Y-%m-%d')
                         }
        return HttpResponse(json.dumps(ajax_response), content_type='application/json')

    def post(self, request, *args, **kwargs):
        form = ContactsAddForm(request.POST)
        if form.is_valid():
            contact_data = {'contact_name': form.cleaned_data['contact_name'],
                            'contact_surname': form.cleaned_data['contact_surname'],
                            'city_name':form.cleaned_data['contact_city'],
                            'country_name':form.cleaned_data['contact_country'],
                            'phone_number':form.cleaned_data['contact_phone'],
                            'email_contact':form.cleaned_data['contact_email'],
                            'date_birthday':form.cleaned_data['contact_b_date'],
                            }
            Contacts.objects.filter(pk=form.cleaned_data['contact_id']).update(**contact_data)

            return HttpResponse(json.dumps({'success': True}),
                                content_type="application/json")
        else:
            return HttpResponse(json.dumps({'success': False,
                                            'errors': [(k, v[0]) for k, v in form.errors.items()]}),
                                content_type="application/json")


def ajax_delete_contact_modal(request):
    if request.method == "POST" and request.is_ajax:
        contact = Contacts.objects.get(pk=request.POST['contact_id'])
        contact.delete()
        return HttpResponse(json.dumps({'success': True}), content_type="application/json")
    else:
        return HttpResponse(json.dumps({'success': False}), content_type="application/json")

@csrf_exempt
def ajax_add_contact_modal(request):

    if request.method == "GET" and request.is_ajax:
        form = ContactsAddForm()

        return HttpResponse(json.dumps({'success': True}),
                            content_type="application/json")

    if request.method == "POST" and request.is_ajax:
        form = ContactsAddForm(request.POST)
        if form.is_valid():
            user_profile = UserProfile.objects.get(user=request.user)
            Contacts.objects.create(contact_name=form.cleaned_data['contact_name'],
                                    contact_surname=form.cleaned_data['contact_surname'],
                                    city_name=form.cleaned_data['contact_city'],
                                    country_name=form.cleaned_data['contact_country'],
                                    phone_number=form.cleaned_data['contact_phone'],
                                    email_contact=form.cleaned_data['contact_email'],
                                    date_birthday=form.cleaned_data['contact_b_date'],
                                    date_add=form.cleaned_data['contact_add_date'],
                                    user_profile=user_profile
                                    )
            return HttpResponse(json.dumps({'success': True}),
                                content_type="application/json")
        else:
            return HttpResponse(json.dumps({'success': False,
                                            'errors': [(k, v[0]) for k, v in form.errors.items()]}),
                                content_type="application/json")
    else:
        return HttpResponse(json.dumps({'success': False}), content_type="application/json")

@csrf_exempt
def upload_csv_file(request):
    if request.method == 'POST':
        csvfile = request.FILES['csvFile']
        fs = FileSystemStorage()

contacts/apps/core/templates/all_contacts.html
{% extends "base.html" %}
{% load static %}
{% block header %}
{% endblock %}
{% block content_wrapper %}
<section class="content-header">
    {% block content-header %}
        <h1>
            All Contacts
        </h1>
        <ol class="breadcrumb">
            <li><a href="{% url 'core:dashboard' %}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li class="active">All Contacts</li>
        </ol>
    {% endblock %}
</section>
<section class="content">
    <div class="col-md-12">
        <div class="box box-primary">
            <div class="box-header">
                <h3 class="box-title">Latest Contacts</h3>
                <button type="button" class="btn btn-primary btn-sm edit_modal pull-right" data-cid="null" id="add_contact"  data-toggle="modal" data-target="#contact_modal">+</button>
            </div>
            <div class="box-body">
                <div class="tab-pane active">
                    <table id="allContactsTable" class="table table-hover" width="100%">
                        <thead>
                            <tr>
                                <th width="1%">ID</th>
                                <th>Name</th>
                                <th>Surname</th>
                                <th class="sorting">City</th>
                                <th>Country</th>
                                <th>Phone</th>
                                <th>Email</th>
                                <th>Date Birthday</th>
                                <th id="date_add">Date Add</th>
                                {% if user.is_superuser %}
                                <th id="user_row" width="15%">User</th>
                                {% else %}
                                <th id="user_row" width="15%"></th>
                                {% endif %}
                                <th>Buttons</th>
                            </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th>
                                <select class="form-control" id="city-filter">
                                <option value="0" selected>All</option>
                                    {% for row in city_name %}
                                    <option value="{{ row }}">{{ row }}</option>
                                    {% endfor %}
                                </select>
                            </th>
                            <th>
                                <select class="form-control" id="country-filter">
                                <option value="0" selected>All</option>
                                    {% for row in country_name %}
                                    <option value="{{ row }}">{{ row }}</option>
                                    {% endfor %}
                                </select>
                            </th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                        </tr>
                    </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>

    <div id="contact_modal" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title" id="contact_title_modal">Manage Contacts Form</h4>
                </div>
                <div class="modal-body">
                    <form class="form-horizontal"> {% csrf_token %}
                        <div class="form-group" hidden>
                            <label for="contact_id" class="col-sm-3 control-label">ID</label>
                            <div class="col-sm-7 " id="contact_id_div">
                                <input id="contact_id" class="form-control" type="text" value="" readonly/>
                                <span class="help-block" id="contact_id_help"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="contact_name" class="col-sm-3 control-label">Contact Name</label>
                            <div class="col-sm-7" id="contact_name_div">
                                <input id="contact_name" class="form-control" type="text" value=null required>
                                <span class="help-block" id="contact_name_help"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="contact_surname" class="col-sm-3 control-label">Contact Surname</label>
                            <div class="col-sm-7" id="contact_surname_div">
                                <input id="contact_surname" class="form-control" type="text" value=null required>
                                <span class="help-block" id="contact_surname_help"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="contact_city" class="col-sm-3 control-label">City</label>
                            <div class="col-sm-7" id="contact_city_div">
                                <input id="contact_city" class="form-control" type="text" value="">
                                <span class="help-block" id="contact_city_help"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="contact_country" class="col-sm-3 control-label">Country</label>
                            <div class="col-sm-7" id="contact_country_div">
                                <input id="contact_country" class="form-control" type="text" value="">
                                <span class="help-block" id="contact_country_help"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="contact_phone" class="col-sm-3 control-label">Mobile phone</label>
                            <div class="col-sm-7" id="contact_phone_div">
                                <input id="contact_phone" class="form-control" type="text" value=null>
                                <span class="help-block" id="contact_phone_help"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="contact_email" class="col-sm-3 control-label">E-mail</label>
                            <div class="col-sm-7" id="contact_email_div">
                                <input id="contact_email" class="form-control" type="email" value=null required>
                                <span class="help-block" id="contact_email_help"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="contact_b_date" class="col-sm-3 control-label">Birthday date:</label>
                            <div class="col-sm-7" id="contact_b_date_div">
                                <div class='input-group date'>
                                    <input type="text" id="contact_b_date" class="form-control">
                                    <span class="help-block" id="contact_b_date_help"></span>
                                    <div class="input-group-addon">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group" disabled="false">
                            <label for="contact_add_date" class="col-sm-3 control-label">Date Add</label>
                            <div class="col-sm-7" id="contact_add_date_div">
                                <div class='input-group date'>
                                    <input type="text" id="contact_add_date" class="form-control">
                                    <span class="help-block" id="contact_add_date_help"></span>
                                    <div class="input-group-addon">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer" >
                    <button type="button" class="btn btn-danger pull-left" id="delete_contact">Delete</button>
                    <button type="button" class="btn btn-warning" id="new_contact" hidden="hidden">Save</button>
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js_bottom %}
    <script type="text/javascript" src="{% static 'js/core/all_contcts_datatable.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugins/fileinput/fileinput.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugins/datepicker/bootstrap-datepicker.js' %}"></script>
{% endblock %}

contacts/apps/core/templates/dashboard.html
{% extends "base.html" %}
{% load staticfiles %}
{% block header %}

{% endblock %}
{% block content_wrapper %}
    <!-- Content Header (Page header) -->
    <section class="content-header">
        {% block content-header %}
            <div class="row">
                <div class="col-md-3">
                    <div class="box-header with-border">
                      <h1 class="box-title"><b></b>Dashboard</b> </h1>
                    </div>
                </div>
                {% if user.is_superuser %}
                <div class="col-lg-3 col-xs-6">
                {% else %}
                <div class="col-md-8">
                {% endif %}
                    <div class="box box-solid box-info ">
                        <div class="box-header with-border">
                        <h2 class="box-title">Total Contacts -<b>{{ count_of_all_contacts }} </b> </h2>
                        </div>
                    </div>
                </div>
                {% if user.is_superuser %}
                <div class="col-lg-3 col-xs-6">
                  <div class="box box-solid box-info ">
                    <div class="box-header with-border">
                      <h2 class="box-title">Total Clients -<b>{{ count_of_all_users }} </b> </h2>
                    </div>
                   </div>
                </div>
                {% endif %}
            </div>
            <ol class="breadcrumb">
            <li><a href="{% url 'core:dashboard' %}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            </ol>
        {% endblock %}
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="col-lg-3 col-xs-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h2 >Data change</h2>
                </div>
                <div class="box-body">
                    <div class="tab-pane active form-group">
                        <p>Welcome to the <b>Contacts programme </b>.
                        You can import your contacts in the file csv or <a href="https://www.getvero.com/"> GetVero</a>
                    </div>
                    <div class="box-info header with-border" >
                        <h3>Contacts All</h3>
                    </div>
                    <div class="form-group" id="upload_contacts">
                        <div class="box-group">
                            <div class="box-header">
                                <label class="control-label"> Import from csv </label>
                            </div>
                            <form action="{% url 'core:upload_csv_file' %}" method="post" id="uploadCsvForm" enctype="multipart/form-data">
                                {% csrf_token %}
                                <label class="control-label">Select file</label>
                                <input type="file" name="csvFile" id="csvFile" data-show-preview="false"
                                       accept=".csv" data-allowed-file-extensions='[".csv"]'>
                                <div class="box-footer">
                                    <button type="submit" id="uploadFile" class="" style="float: right;">Upload</button>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="form-group" id="import_csv" hidden>
                        <div class="box-info">
                            <p id="csv_file_name" ><b>Upload successful</b></p>
                            <div class="box-footer">
                                <button id = "contacts_csv" class="pull-right"> Add contacts with csv-file </button>
                            </div>
                        </div>
                        <div class="box-footer">
                            <br>
                        </div>
                    </div>
                    <div class="form-group">
                            <div class="box-header">
                                <label> Export contacts in GetVero </label>
                            </div>
                           <div class="box-info">
                               <div class="box-footer">
                                 <button id = "contacts_vero" class="pull-right"> Export </button>
                               </div>
                         </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="box box-primary">
                <div class="box-header">
                    <h3 class="box-title">Latest Contacts</h3>
                </div>
                <div class="box-body">
                    <div class="tab-pane active">
                        <table id="contactTable" class="table table-hover" width="100%">
                            <thead>
                            <tr>
                                <th>ID </th>
                                <th>Name</th>
                                <th>Surname</th>
                                <th>City</th>
                                <th>Country</th>
                                <th>Phone</th>
                                <th>Email</th>
                                <th>Date Birthday</th>
                                <th>Date Add</th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    <div>
    </section>

    <div id="ModalVero" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <!-- Header modal window -->
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title">Export contacts in GetVero</h4>
                </div>
                <!-- Body modal window -->
                <div class="modal-body">
                    <h4 id="question">Are you sure that you want to export contacts to GetVero?</h4>
                    <div id="overlay" hidden>
                        <div id="vero_in_process">
                            <p class="text-center">
                            <strong>Data export in progress, this can take a few minutes...</strong>
                            <i class="fa fa-refresh fa-spin"></i>
                            </p>
{#                            <img src="{% static 'images/moving_gears.gif' %}" class="img-responsive center-block">#}
                        </div>
                    </div>
                </div>
                <!-- Footer modal window -->
                <div class="modal-footer" id="footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                    <button id="ExportVero" type="button" class="btn btn-warning pull-left">Export</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js_bottom %}
    <script src="{% static 'js/core/dashboard.js' %}"></script>
{% endblock %}